
[loaders]
	load_dungeons_module = true
	load_kuudra_module = true
	load_staff_module = false
	load_alerts_module = true

[dungeons]
	secrets_per_run = true

	[dungeons.party_finder]
		party_finder = true
		party_finder_floor = "F0"
		blood_mob_count = true
		cata_50_date = true
		mobs_per_run = true
		personal_bests = true
		cata_level = true
		tank_party_finder_items = "[     \"TERMINATOR\",     \"TANK_WITHER_HELMET\",     \"TANK_WITHER_CHESTPLATE\",     \"TANK_WITHER_LEGGINGS\",     \"TANK_WITHER_BOOTS\",     \"LAST_BREATH\",     \"POWER_WITHER_HELMET\",     \"POWER_WITHER_CHESTPLATE\",     \"POWER_WITHER_LEGGINGS\",     \"POWER_WITHER_BOOTS\",     \"SOUL_WHIP\",     \"AXE_OF_THE_SHREDDED\" ]"
		unique_pets = true
		mage_party_finder_items = "[     \"DARK_CLAYMORE\",     \"WISE_WITHER_HELMET\",     \"WISE__WITHER_CHESTPLATE\",     \"WISE_WITHER_LEGGINGS\",     \"WISE_WITHER_BOOTS\",     \"LAST_BREATH\",     \"RAGNAROCK_AXE\" ]"
		death_count = true
		secret_count = true
		berserk_party_finder_items = "[     \"TERMINATOR\",     \"DARK_CLAYMORE\",     \"RAGNAROCK_AXE\" ]"
		shitter_list = true
		healer_party_finder_items = "[     \"TERMINATOR\",     \"SOUL_WHIP\",     \"POWER_WITHER_HELMET\",     \"POWER_WITHER_CHESTPLATE\",     \"POWER_WITHER_LEGGINGS\",     \"POWER_WITHER_BOOTS\" ]"
		show_own_stats_in_party_finder = false
		ender_chest_and_backpack_shown = false
		party_finder_items = "[     \"HYPERION\",     \"SCYLLA\",     \"ASTRAEA\",     \"VALKYRIE\",     \"NECRON_BLADE\",     \"DARK_CLAYMORE\",     \"POWER_WITHER_HELMET\",     \"POWER_WITHER_CHESTPLATE\",     \"POWER_WITHER_LEGGINGS\",     \"POWER_WITHER_BOOTS\",     \"SPEED_WITHER_HELMET\",     \"SPEED_WITHER_CHESTPLATE\",     \"SPEED_WITHER_LEGGINGS\",     \"SPEED_WITHER_BOOTS\",     \"SPRING_BOOTS\",     \"JERRY_STAFF\",     \"DIAMOND_PICKAXE\",     \"ALPHA_PICK\",     \"STONK\" ]"
		archer_party_finder_items = "[     \"TERMINATOR\",     \"RAGNAROCK_AXE\",     \"POWER_WITHER_HELMET\",     \"POWER_WITHER_CHESTPLATE\",     \"POWER_WITHER_LEGGINGS\",     \"POWER_WITHER_BOOTS\" ]"

[misc]
	healing_wand_alerts = false
	wither_cloak_alerts = true
	cells_alignment_alerts = false
	katana_alerts = false
	weird_tuba_alerts = false
	ice_spray_alerts = false
	low_soulflow_amount = "500"

