
[loaders]
	load_dungeons_module = true
	load_kuudra_module = true
	load_alerts_module = true

[dungeons]
	secrets_per_run = true
	goldor_counts = false

	[dungeons.party_finder]
		party_finder = true
		party_finder_floor = "M7"
		berserk_party_finder_items = "[     \"TERMINATOR\",     \"DARK_CLAYMORE\",     \"RAGNAROCK_AXE\" ]"
		healer_party_finder_items = "[     \"TERMINATOR\",     \"SOUL_WHIP\",     \"POWER_WITHER_HELMET\",     \"POWER_WITHER_CHESTPLATE\",     \"POWER_WITHER_LEGGINGS\",     \"POWER_WITHER_BOOTS\" ]"
		show_own_stats_in_party_finder = true
		ender_chest_and_backpack_shown = false
		party_finder_items = "[     \"HYPERION\",     \"SCYLLA\",     \"ASTRAEA\",     \"VALKYRIE\",     \"NECRON_BLADE\",     \"DARK_CLAYMORE\",     \"POWER_WITHER_HELMET\",     \"POWER_WITHER_CHESTPLATE\",     \"POWER_WITHER_LEGGINGS\",     \"POWER_WITHER_BOOTS\",     \"SPEED_WITHER_HELMET\",     \"SPEED_WITHER_CHESTPLATE\",     \"SPEED_WITHER_LEGGINGS\",     \"SPEED_WITHER_BOOTS\",     \"SPRING_BOOTS\",     \"JERRY_STAFF\",     \"DIAMOND_PICKAXE\",     \"ALPHA_PICK\",     \"STONK\" ]"
		archer_party_finder_items = "[     \"TERMINATOR\",     \"RAGNAROCK_AXE\",     \"POWER_WITHER_HELMET\",     \"POWER_WITHER_CHESTPLATE\",     \"POWER_WITHER_LEGGINGS\",     \"POWER_WITHER_BOOTS\" ]"
		tank_party_finder_items = "[     \"TERMINATOR\",     \"TANK_WITHER_HELMET\",     \"TANK_WITHER_CHESTPLATE\",     \"TANK_WITHER_LEGGINGS\",     \"TANK_WITHER_BOOTS\",     \"LAST_BREATH\",     \"POWER_WITHER_HELMET\",     \"POWER_WITHER_CHESTPLATE\",     \"POWER_WITHER_LEGGINGS\",     \"POWER_WITHER_BOOTS\",     \"SOUL_WHIP\",     \"AXE_OF_THE_SHREDDED\" ]"
		mage_party_finder_items = "[     \"DARK_CLAYMORE\",     \"WISE_WITHER_HELMET\",     \"WISE__WITHER_CHESTPLATE\",     \"WISE_WITHER_LEGGINGS\",     \"WISE_WITHER_BOOTS\",     \"LAST_BREATH\",     \"RAGNAROCK_AXE\" ]"

	[dungeons.dungeon_routes]
		render_full_block = true
		route_text = true
		transparency_on_text = 800
		transparency_on_block = 177
		route_sharing = true
		line_to_red = true
		transparency_on_line = 754
		line_to_yellow = true
		note_gui = false
		dungeon_routes = true

[misc]
	healing_wand_alerts = false
	wither_cloak_alerts = true
	cells_alignment_alerts = false
	katana_alerts = false
	weird_tuba_alerts = false
	remove_selfie_mode = false
	ice_spray_alerts = false
	low_soulflow_amount = "500"

